sudo: false
language: ruby
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
before_install:
  - gem install bundler
script:
  - bundle exec rake test:units FOG_MOCK=true COVERAGE=true
  - bundle exec rake test:integration FOG_MOCK=true
  - bundle exec rake rubocop
